name: Scrape air quality data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "5,25,45 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Fetch latest data
        run: |-
          curl https://www.airnowapi.org/aq/data/?parameters=PM25&BBOX=-115.947342,44.298048,-103.598709,49.172497&dataType=B&format=application/json&verbose=1&nowcastonly=1&includerawconcentrations=1&API_KEY=40F0E34D-07B2-4DF3-B8B8-8563AD479DE3 | jq '.'  > mt-air-quality.json
      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
